/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{astro,html,js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#fff8f5",
        "on-background": "#231a11",
        surface: "#fff8f5",
        "surface-dim": "#ead6c9",
        "surface-bright": "#fff8f5",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fff1e8",
        "surface-container": "#feeadc",
        "surface-container-high": "#f8e5d7",
        "surface-container-highest": "#f3dfd1",
        "surface-muted": "#F9F9F9",
        "surface-variant": "#f3dfd1",
        "on-surface": "#231a11",
        "on-surface-variant": "#564334",
        "inverse-surface": "#3a2e25",
        "inverse-on-surface": "#ffeee2",
        outline: "#897362",
        "outline-variant": "#dcc2ae",
        "surface-tint": "#8e4e00",
        primary: "#8e4e00",
        "on-primary": "#ffffff",
        "primary-container": "#ff9000",
        "on-primary-container": "#633400",
        "inverse-primary": "#ffb779",
        "primary-fixed": "#ffdcc1",
        "primary-fixed-dim": "#ffb779",
        secondary: "#5f5e5e",
        "on-secondary": "#ffffff",
        "secondary-container": "#e5e2e1",
        "on-secondary-container": "#656464",
        tertiary: "#00658d",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#00b8fd",
        "on-tertiary-container": "#004562",
        "rotary-blue": "#005DAA",
        "peace-teal": "#008B94",
        "focus-red": "#D91B5C",
        error: "#b3261e",
        "on-error": "#ffffff",
        "error-container": "#f9dedc",
        "on-error-container": "#410e0b",
        ink: "#111111",
      },
      fontFamily: {
        display: ["Montserrat", "system-ui", "sans-serif"],
        body: ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-hero": [
          "clamp(2.5rem, 6vw, 4rem)",
          { lineHeight: "1.1", fontWeight: "800", letterSpacing: "-0.02em" },
        ],
        "headline-lg": [
          "clamp(1.75rem, 3vw, 2.5rem)",
          { lineHeight: "1.2", fontWeight: "700" },
        ],
        "headline-md": ["1.5rem", { lineHeight: "2rem", fontWeight: "600" }],
        "body-lg": ["1.125rem", { lineHeight: "1.75rem", fontWeight: "400" }],
        "body-md": ["1rem", { lineHeight: "1.5rem", fontWeight: "400" }],
        "label-caps": [
          "0.75rem",
          { lineHeight: "1rem", fontWeight: "700", letterSpacing: "0.1em" },
        ],
        metadata: ["0.875rem", { lineHeight: "1.25rem", fontWeight: "500" }],
      },
      maxWidth: {
        container: "1280px",
      },
      spacing: {
        gutter: "24px",
        "section-gap": "80px",
        "component-padding": "24px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
      },
      boxShadow: {
        lift: "0 10px 20px -5px rgba(142, 78, 0, 0.1)",
      },
    },
  },
  plugins: [],
};
